### ISSUE TITLE
Group.remote.get_members_ids error

### ISSUE THREAD

**Issue by Andertaker** [ramusus/django-vkontakte-groups#4]
https://github.com/ramusus/django-vkontakte-groups/blob/master/vkontakte_groups/models.py#L52

```
group = Group.remote.fetch(ids=[40376083])[0]
print Group.remote.get_members_ids(group)
```

вызывает ошибку

> get_members_ids() takes exactly 2 arguments (1 given)

файл django-vkontakte-api/vkontakte_api/decorators.py in wrapper строка 49

```
            def fetch_something(self, ..., *kwargs)
               ....
                instances = func(self, *args, **kwargs)
                ...

```

или я что-то не так делаю

**Comment by ramusus** [comment]
```
Group.remote.get_members_ids(group=group)
```
